apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sriayyag-sriayyag-poi-map-app-dev
  annotations:
    argocd/app-name: sriayyag-sriayyag-poi-map-app-dev
    backstage.io/kubernetes-id: sriayyag-sriayyag-poi-map-app-dev
    backstage.io/kubernetes-namespace: sriayyag
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=sriayyag-sriayyag-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/sriayyag-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/sriayyag/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/sriayyag/deployments/sriayyag-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/sriayyag-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://sriayyag-poi-map-app-sriayyag.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/sriayyag"
  system: workshop-system-sriayyag
  consumesApis:
    - gateway-api-sriayyag
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-sriayyag
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/sriayyag"
